name        : totem
version     : 3.16.0
release     : 4
source      :
    - http://ftp.acc.umu.se/pub/GNOME/sources/totem/3.16/totem-3.16.0.tar.xz : 69b109533b592683eecf0274262f8247219f0e44134b395a6ed36403d8d166e3
homepage    : http://gnome.org
license     :
    - GPL-2.0
summary     : GNOME Multimedia Player
builddeps   :
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(totem-plparser)
    - pkgconfig(grilo-0.2)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(libpeas-gtk-1.0)
    - gstreamer-1.0-plugins-good
    - itstool
clang       : no
description : |
    Videos, also known as Totem, is the official movie player of the GNOME desktop environment. It features a searchable list of local videos, and DVDs, as well as local network video shares (using UPnP/DLNA) and video highlights from a number of web sites.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
