name       : totem
version    : 3.26.2
release    : 16
source     :
    - https://download.gnome.org/sources/totem/3.26/totem-3.26.2.tar.xz : cf8c49941f37e326353e5ede621350f78d2658f7cef73bf92aeedfa1a98e9ed2
license    : GPL-2.0
component  : multimedia.video
summary    : GNOME Multimedia Player
description: |
    Videos, also known as Totem, is the official movie player of the GNOME desktop environment. It features a searchable list of local videos, and DVDs, as well as local network video shares (using UPnP/DLNA) and video highlights from a number of web sites.
clang      : no
builddeps  :
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(grilo-0.3)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(totem-plparser)
    - gstreamer-1.0-plugins-good
    - gtk-doc
    - itstool
    - pylint
    - vala
rundeps    :
    - grilo-plugins
setup      : |
    export LC_ALL=en_US.utf8
    %meson_configure -Denable-gtk-doc=true -Denable-python=yes
build      : |
    export LC_ALL=en_US.utf8
    %meson_build -j1
install    : |
    export LC_ALL=en_US.utf8
    %meson_install
